const emojiList = [{
	"id": 277,
	"type": "common",
	"key": "weixiao",
	"name": "微笑",
	"url": "weixiao.png",
	"sort": 1,
	"remark": "",
	"name_en": "Smile"
}, {
	"id": 278,
	"type": "common",
	"key": "piezui",
	"name": "撇嘴",
	"url": "piezui.png",
	"sort": 2,
	"remark": "",
	"name_en": "Grimace"
}, {
	"id": 279,
	"type": "common",
	"key": "xihuan",
	"name": "喜欢",
	"url": "xihuan.png",
	"sort": 3,
	"remark": "",
	"name_en": "Drool"
}, {
	"id": 280,
	"type": "common",
	"key": "mengbi",
	"name": "懵逼",
	"url": "mengbi.png",
	"sort": 4,
	"remark": "",
	"name_en": "Scowl"
}, {
	"id": 281,
	"type": "common",
	"key": "ku",
	"name": "酷",
	"url": "ku.png",
	"sort": 5,
	"remark": "",
	"name_en": "CoolGuy"
}, {
	"id": 282,
	"type": "common",
	"key": "daku",
	"name": "大哭",
	"url": "daku.png",
	"sort": 6,
	"remark": "",
	"name_en": "Sob"
}, {
	"id": 283,
	"type": "common",
	"key": "bizui",
	"name": "闭嘴",
	"url": "bizui.png",
	"sort": 7,
	"remark": "",
	"name_en": "Silent"
}, {
	"id": 284,
	"type": "common",
	"key": "shuijiao",
	"name": "睡觉",
	"url": "shuijiao.png",
	"sort": 8,
	"remark": "",
	"name_en": "Sleep"
}, {
	"id": 285,
	"type": "common",
	"key": "jusang",
	"name": "沮丧",
	"url": "jusang.png",
	"sort": 9,
	"remark": "",
	"name_en": "Dispirited"
}, {
	"id": 286,
	"type": "common",
	"key": "ganga",
	"name": "尴尬",
	"url": "ganga.png",
	"sort": 10,
	"remark": "",
	"name_en": "Awkward"
}, {
	"id": 287,
	"type": "common",
	"key": "nu",
	"name": "怒",
	"url": "nu.png",
	"sort": 11,
	"remark": "",
	"name_en": "Angry"
}, {
	"id": 288,
	"type": "common",
	"key": "xixi",
	"name": "嘻嘻",
	"url": "xixi.png",
	"sort": 12,
	"remark": "",
	"name_en": "Grin"
}, {
	"id": 289,
	"type": "common",
	"key": "maimeng",
	"name": "卖萌",
	"url": "maimeng.png",
	"sort": 13,
	"remark": "",
	"name_en": "Tongue"
}, {
	"id": 290,
	"type": "common",
	"key": "jidong",
	"name": "激动",
	"url": "jidong.png",
	"sort": 14,
	"remark": "",
	"name_en": "Excite"
}, {
	"id": 291,
	"type": "common",
	"key": "buyue",
	"name": "不悦",
	"url": "buyue.png",
	"sort": 15,
	"remark": "",
	"name_en": "Displeasure"
}, {
	"id": 292,
	"type": "common",
	"key": "hai",
	"name": "嗨",
	"url": "hai.png",
	"sort": 16,
	"remark": "",
	"name_en": "Hey"
}, {
	"id": 293,
	"type": "common",
	"key": "jingkong",
	"name": "惊恐",
	"url": "jingkong.png",
	"sort": 17,
	"remark": "",
	"name_en": "Panic"
}, {
	"id": 294,
	"type": "common",
	"key": "outu",
	"name": "呕吐",
	"url": "outu.png",
	"sort": 18,
	"remark": "",
	"name_en": "Puke"
}, {
	"id": 295,
	"type": "common",
	"key": "touxiao",
	"name": "偷笑",
	"url": "touxiao.png",
	"sort": 19,
	"remark": "",
	"name_en": "Chuckle"
}, {
	"id": 296,
	"type": "common",
	"key": "keai",
	"name": "可爱",
	"url": "keai.png",
	"sort": 20,
	"remark": "",
	"name_en": "Joyful"
}, {
	"id": 297,
	"type": "common",
	"key": "fanbaiyan",
	"name": "翻白眼",
	"url": "fanbaiyan.png",
	"sort": 21,
	"remark": "",
	"name_en": "Slight"
}, {
	"id": 298,
	"type": "common",
	"key": "eishima",
	"name": "诶是吗",
	"url": "eishima.png",
	"sort": 22,
	"remark": "",
	"name_en": "eishima"
}, {
	"id": 299,
	"type": "common",
	"key": "kun",
	"name": "困",
	"url": "kun.png",
	"sort": 23,
	"remark": "",
	"name_en": "Drowsy"
}, {
	"id": 300,
	"type": "common",
	"key": "wenhaolian",
	"name": "问号脸",
	"url": "wenhaolian.png",
	"sort": 24,
	"remark": "",
	"name_en": "Shocked"
}, {
	"id": 301,
	"type": "common",
	"key": "han",
	"name": "汗",
	"url": "han.png",
	"sort": 25,
	"remark": "",
	"name_en": "Sweat"
}, {
	"id": 302,
	"type": "common",
	"key": "daxiao",
	"name": "大笑",
	"url": "daxiao.png",
	"sort": 26,
	"remark": "",
	"name_en": "Laugh"
}, {
	"id": 303,
	"type": "common",
	"key": "jizhi",
	"name": "机智",
	"url": "jizhi.png",
	"sort": 27,
	"remark": "",
	"name_en": "Smart"
}, {
	"id": 304,
	"type": "common",
	"key": "caimi",
	"name": "财迷",
	"url": "caimi.png",
	"sort": 28,
	"remark": "",
	"name_en": "Miser"
}, {
	"id": 305,
	"type": "common",
	"key": "wuyu",
	"name": "无语",
	"url": "wuyu.png",
	"sort": 29,
	"remark": "",
	"name_en": "Wordless"
}, {
	"id": 306,
	"type": "common",
	"key": "yiwen",
	"name": "疑问",
	"url": "yiwen.png",
	"sort": 30,
	"remark": "",
	"name_en": "Confused"
}, {
	"id": 307,
	"type": "common",
	"key": "xu",
	"name": "嘘",
	"url": "xu.png",
	"sort": 31,
	"remark": "",
	"name_en": "Shh"
}, {
	"id": 308,
	"type": "common",
	"key": "yun",
	"name": "晕",
	"url": "yun.png",
	"sort": 32,
	"remark": "",
	"name_en": "Dizzy"
}, {
	"id": 309,
	"type": "common",
	"key": "wunai",
	"name": "无奈",
	"url": "wunai.png",
	"sort": 33,
	"remark": "",
	"name_en": "helpless"
}, {
	"id": 310,
	"type": "common",
	"key": "feiqiulei",
	"name": "非酋泪",
	"url": "feiqiulei.png",
	"sort": 34,
	"remark": "",
	"name_en": "Toasted"
}, {
	"id": 311,
	"type": "common",
	"key": "kulou",
	"name": "骷髅",
	"url": "kulou.png",
	"sort": 35,
	"remark": "",
	"name_en": "Skull"
}, {
	"id": 312,
	"type": "common",
	"key": "shengbing",
	"name": "生病",
	"url": "shengbing.png",
	"sort": 36,
	"remark": "",
	"name_en": "Sick"
}, {
	"id": 313,
	"type": "common",
	"key": "zaijian",
	"name": "再见",
	"url": "zaijian.png",
	"sort": 37,
	"remark": "",
	"name_en": "Bye"
}, {
	"id": 314,
	"type": "common",
	"key": "yunbei",
	"name": "允悲",
	"url": "yunbei.png",
	"sort": 38,
	"remark": "",
	"name_en": "Facepalm"
}, {
	"id": 315,
	"type": "common",
	"key": "koubi",
	"name": "抠鼻",
	"url": "koubi.png",
	"sort": 39,
	"remark": "",
	"name_en": "NosePick"
}, {
	"id": 316,
	"type": "common",
	"key": "guzhang",
	"name": "鼓掌",
	"url": "guzhang.png",
	"sort": 40,
	"remark": "",
	"name_en": "Clap"
}, {
	"id": 317,
	"type": "common",
	"key": "zhoumei",
	"name": "皱眉",
	"url": "zhoumei.png",
	"sort": 41,
	"remark": "",
	"name_en": "Frown"
}, {
	"id": 318,
	"type": "common",
	"key": "huaixiao",
	"name": "坏笑",
	"url": "huaixiao.png",
	"sort": 42,
	"remark": "",
	"name_en": "Trick"
}, {
	"id": 319,
	"type": "common",
	"key": "bishi",
	"name": "鄙视",
	"url": "bishi.png",
	"sort": 43,
	"remark": "",
	"name_en": "Pooh-pooh"
}, {
	"id": 320,
	"type": "common",
	"key": "nidongde",
	"name": "你懂的",
	"url": "nidongde.png",
	"sort": 44,
	"remark": "",
	"name_en": "Sly"
}, {
	"id": 321,
	"type": "common",
	"key": "kuaikule",
	"name": "快哭了",
	"url": "kuaikule.png",
	"sort": 45,
	"remark": "",
	"name_en": "Whimper"
}, {
	"id": 322,
	"type": "common",
	"key": "xiaoku",
	"name": "笑哭",
	"url": "xiaoku.png",
	"sort": 46,
	"remark": "",
	"name_en": "Dumbfounding"
}, {
	"id": 323,
	"type": "common",
	"key": "doge",
	"name": "doge",
	"url": "doge.png",
	"sort": 47,
	"remark": "",
	"name_en": "doge"
}, {
	"id": 324,
	"type": "common",
	"key": "wu",
	"name": "污",
	"url": "wu.png",
	"sort": 48,
	"remark": "",
	"name_en": "Evil"
}, {
	"id": 325,
	"type": "common",
	"key": "xieyanxiao",
	"name": "斜眼笑",
	"url": "xieyanxiao.png",
	"sort": 49,
	"remark": "",
	"name_en": "Satanic"
}, {
	"id": 326,
	"type": "common",
	"key": "jingxi",
	"name": "惊喜",
	"url": "jingxi.png",
	"sort": 50,
	"remark": "",
	"name_en": "Surperise"
}, {
	"id": 327,
	"type": "common",
	"key": "sikao",
	"name": "思考",
	"url": "sikao.png",
	"sort": 51,
	"remark": "",
	"name_en": "Thinking"
}, {
	"id": 328,
	"type": "common",
	"key": "jianxiao",
	"name": "奸笑",
	"url": "jianxiao.png",
	"sort": 52,
	"remark": "",
	"name_en": "Grin"
}, {
	"id": 329,
	"type": "common",
	"key": "haixiu",
	"name": "害羞",
	"url": "haixiu.png",
	"sort": 53,
	"remark": "",
	"name_en": "Shy"
}, {
	"id": 330,
	"type": "common",
	"key": "zan",
	"name": "赞",
	"url": "zan.png",
	"sort": 54,
	"remark": "",
	"name_en": "Good"
}, {
	"id": 331,
	"type": "common",
	"key": "xia",
	"name": "吓",
	"url": "xia.png",
	"sort": 55,
	"remark": "",
	"name_en": "Scare"
}, {
	"id": 332,
	"type": "common",
	"key": "qinqin",
	"name": "亲亲",
	"url": "qinqin.png",
	"sort": 56,
	"remark": "",
	"name_en": "Kiss"
}, {
	"id": 333,
	"type": "common",
	"key": "zhayan",
	"name": "眨眼",
	"url": "zhayan.png",
	"sort": 57,
	"remark": "",
	"name_en": "Blink"
}, {
	"id": 334,
	"type": "common",
	"key": "jujue",
	"name": "拒绝",
	"url": "jujue.png",
	"sort": 58,
	"remark": "",
	"name_en": "Refuse"
}, {
	"id": 335,
	"type": "common",
	"key": "zoukai",
	"name": "走开",
	"url": "zoukai.png",
	"sort": 59,
	"remark": "",
	"name_en": "Getout"
}, {
	"id": 336,
	"type": "common",
	"key": "chaofenglian",
	"name": "嘲讽脸",
	"url": "chaofenglian.png",
	"sort": 60,
	"remark": "",
	"name_en": "Sarcasm"
}, {
	"id": 337,
	"type": "common",
	"key": "chibaomihua",
	"name": "吃爆米花",
	"url": "chibaomihua.png",
	"sort": 61,
	"remark": "",
	"name_en": "EatPopcorn"
}, {
	"id": 338,
	"type": "common",
	"key": "chibing",
	"name": "吃饼",
	"url": "chibing.png",
	"sort": 62,
	"remark": "",
	"name_en": "EatCake"
}, {
	"id": 339,
	"type": "common",
	"key": "chigua",
	"name": "吃瓜",
	"url": "chigua.png",
	"sort": 63,
	"remark": "",
	"name_en": "EatMelon"
}, {
	"id": 340,
	"type": "common",
	"key": "chijitui",
	"name": "吃鸡腿",
	"url": "chijitui.png",
	"sort": 64,
	"remark": "",
	"name_en": "Eatdrumstick"
}, {
	"id": 341,
	"type": "common",
	"key": "chimian",
	"name": "吃面",
	"url": "chimian.png",
	"sort": 65,
	"remark": "",
	"name_en": "EatNoodle"
}, {
	"id": 342,
	"type": "common",
	"key": "qiang",
	"name": "强",
	"url": "qiang.png",
	"sort": 66,
	"remark": "",
	"name_en": "ThumbsUp"
}, {
	"id": 343,
	"type": "common",
	"key": "ruo",
	"name": "弱",
	"url": "ruo.png",
	"sort": 67,
	"remark": "",
	"name_en": "ThumbsDown"
}, {
	"id": 344,
	"type": "common",
	"key": "hezuo",
	"name": "合作",
	"url": "hezuo.png",
	"sort": 68,
	"remark": "",
	"name_en": "Shake"
}, {
	"id": 345,
	"type": "common",
	"key": "shengli",
	"name": "胜利",
	"url": "shengli.png",
	"sort": 69,
	"remark": "",
	"name_en": "Peace"
}, {
	"id": 346,
	"type": "common",
	"key": "quantou",
	"name": "拳头",
	"url": "quantou.png",
	"sort": 70,
	"remark": "",
	"name_en": "Fist"
}, {
	"id": 347,
	"type": "common",
	"key": "haode",
	"name": "好的",
	"url": "haode.png",
	"sort": 71,
	"remark": "",
	"name_en": "OK"
}, {
	"id": 348,
	"type": "common",
	"key": "bixin",
	"name": "比心",
	"url": "bixin.png",
	"sort": 72,
	"remark": "",
	"name_en": "Love"
}, {
	"id": 349,
	"type": "common",
	"key": "qidao",
	"name": "祈祷",
	"url": "qidao.png",
	"sort": 73,
	"remark": "",
	"name_en": "Pray"
}, {
	"id": 350,
	"type": "common",
	"key": "baoquan",
	"name": "抱拳",
	"url": "baoquan.png",
	"sort": 74,
	"remark": "",
	"name_en": "Salute"
}, {
	"id": 351,
	"type": "common",
	"key": "jirou",
	"name": "肌肉",
	"url": "jirou.png",
	"sort": 75,
	"remark": "",
	"name_en": "Power"
}, {
	"id": 352,
	"type": "common",
	"key": "xiong",
	"name": "熊",
	"url": "xiong.png",
	"sort": 76,
	"remark": "",
	"name_en": "Bear"
}, {
	"id": 353,
	"type": "common",
	"key": "waixingren",
	"name": "外星人",
	"url": "waixingren.png",
	"sort": 77,
	"remark": "",
	"name_en": "Alien"
}, {
	"id": 354,
	"type": "common",
	"key": "youling",
	"name": "幽灵",
	"url": "youling.png",
	"sort": 78,
	"remark": "",
	"name_en": "Ghost"
}, {
	"id": 355,
	"type": "common",
	"key": "bianbian",
	"name": "便便",
	"url": "bianbian.png",
	"sort": 79,
	"remark": "",
	"name_en": "Shit"
}, {
	"id": 356,
	"type": "common",
	"key": "wanan",
	"name": "晚安",
	"url": "wanan.png",
	"sort": 80,
	"remark": "",
	"name_en": "Goodnight"
}, {
	"id": 357,
	"type": "common",
	"key": "zaoan",
	"name": "早安",
	"url": "zaoan.png",
	"sort": 81,
	"remark": "",
	"name_en": "Goodmorning"
}, {
	"id": 358,
	"type": "common",
	"key": "xigua",
	"name": "西瓜",
	"url": "xigua.png",
	"sort": 82,
	"remark": "",
	"name_en": "Watermelon"
}, {
	"id": 359,
	"type": "common",
	"key": "caidao",
	"name": "菜刀",
	"url": "caidao.png",
	"sort": 83,
	"remark": "",
	"name_en": "Chopper"
}, {
	"id": 360,
	"type": "common",
	"key": "zhadan",
	"name": "炸弹",
	"url": "zhadan.png",
	"sort": 84,
	"remark": "",
	"name_en": "Boom"
}, {
	"id": 361,
	"type": "common",
	"key": "aixin",
	"name": "爱心",
	"url": "aixin.png",
	"sort": 85,
	"remark": "",
	"name_en": "Heart"
}, {
	"id": 362,
	"type": "common",
	"key": "xinsui",
	"name": "心碎",
	"url": "xinsui.png",
	"sort": 86,
	"remark": "",
	"name_en": "BrokenHeart"
}, {
	"id": 363,
	"type": "common",
	"key": "feiji",
	"name": "飞机",
	"url": "feiji.png",
	"sort": 87,
	"remark": "",
	"name_en": "Plane"
}, {
	"id": 364,
	"type": "common",
	"key": "lazhu",
	"name": "蜡烛",
	"url": "lazhu.png",
	"sort": 88,
	"remark": "",
	"name_en": "Candle"
}, {
	"id": 365,
	"type": "common",
	"key": "pijiu",
	"name": "啤酒",
	"url": "pijiu.png",
	"sort": 89,
	"remark": "",
	"name_en": "Beer"
}, {
	"id": 366,
	"type": "common",
	"key": "yaowan",
	"name": "药丸",
	"url": "yaowan.png",
	"sort": 90,
	"remark": "",
	"name_en": "Pill"
}, {
	"id": 367,
	"type": "common",
	"key": "bingqilin",
	"name": "冰淇淋",
	"url": "bingqilin.png",
	"sort": 91,
	"remark": "",
	"name_en": "IceCream"
}, {
	"id": 368,
	"type": "common",
	"key": "hua",
	"name": "花",
	"url": "hua.png",
	"sort": 92,
	"remark": "",
	"name_en": "flower"
}]

export default emojiList;